---
# Command to start on workspace startup (optional)
tasks:
  - init: ./gradlew build
    command: ./gradlew bootRun

# Ports to expose on workspace startup (optional)
ports:
  - port: 8080
    onOpen: ignore
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-debug
    - pkief.material-icon-theme
#    - cool2k.vscode-lombok